language: php

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2

sudo: false

install:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit