version: 2

jobs:

  php74:
    docker:
      - image: circleci/php:7.4-cli

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests / Symfony 4^3
          command: |
            composer update -n --prefer-dist --prefer-stable
            php vendor/bin/phpunit

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist
            php vendor/bin/phpunit

  php80:
    docker:
      - image: circleci/php:8.0-cli

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            composer update -n --prefer-dist
            php vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - php74
      - php80