version: 2

jobs:
  php72:
    docker:
      - image: circleci/php:7.2-cli

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests / Symfony 4^3
          command: |
            composer update -n --prefer-dist --prefer-stable --no-suggest
            php vendor/bin/phpunit

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist --no-suggest
            php vendor/bin/phpunit

  php74:
    docker:
      - image: circleci/php:7.4-cli

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests / Symfony 4^3
          command: |
            composer update -n --prefer-dist --prefer-stable --no-suggest
            php vendor/bin/phpunit

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist --no-suggest
            php vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - php72
      - php74