version: 2

jobs:

  php72:
    docker:
      - image: circleci/php:7.2-cli

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests - minimum
          command: |
            composer update -n --prefer-dist --prefer-lowest
            php vendor/bin/phpunit

  php73:
    docker:
      - image: circleci/php:7.3-cli

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests - minimum
          command: |
            composer update -n --prefer-dist --prefer-lowest
            php vendor/bin/phpunit

  php74:
    docker:
      - image: circleci/php:7.4-cli

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            composer update -n --prefer-dist
            php vendor/bin/phpunit

  php80:
    docker:
      - image: circleci/php:8.0-cli

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            composer update -n --prefer-dist
            php vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - php72
      - php73
      - php74
      - php80